name: TestsMSI

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Windows Installer
    runs-on: windows-latest
    timeout-minutes: 60
    strategy:
      matrix:
        type: [x86]
    env:
      IncludeFreethreaded: true
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'python/cpython'
        fetch-tags: 'v3.12.2'
    - name: Build CPython installer
      run: .\Tools\msi\build.bat --doc -${{ matrix.type }}
    - uses: actions/upload-artifact@v4
      with:
        name: CPythonInstaller
        path: ./PCbuild/**/*.exe
        compression-level: 9
